console.log(location.href);

let mapDiv = document.getElementById('map');
let latDiv = document.getElementById('lat');
let lngDiv = document.getElementById('lng');
let distDiv = document.getElementById('dist');

let pos1 = { // 역삼역 1번출구의 위경도
  lat: 37.5004462,
  lng: 127.037236,
};

let position = new naver.maps.LatLng(pos1.lat, pos1.lng);
let map = new naver.maps.Map(mapDiv, {
  center: position,
});

let marker = new naver.maps.Marker({
    position: position,
    map: map
});

naver.maps.Event.addListener(map, 'click', function(e) {
  console.log(e.coord);
    marker.setPosition(e.coord);
    const pos = {
      lat: e.coord._lat,
      lng: e.coord._lng,
    };
    latDiv.value = e.coord._lat;
    lngDiv.value = e.coord._lng;
    distDiv.value = Math.round(getDistance(pos1, pos));
});



function getDistance(pos1, pos2) {
  // Haversine 공식 이용, generated by chat GPT
  const toRadians = (degrees) => {
    return degrees * (Math.PI / 180);
  };

  const earthRadius = 6371e3; // Earth's radius in meters
  const lat1 = toRadians(pos1.lat);
  const lat2 = toRadians(pos2.lat);
  const deltaLat = toRadians(pos2.lat - pos1.lat);
  const deltaLng = toRadians(pos2.lng - pos1.lng);

  const a = Math.sin(deltaLat / 2) * Math.sin(deltaLat / 2) +
            Math.cos(lat1) * Math.cos(lat2) *
            Math.sin(deltaLng / 2) * Math.sin(deltaLng / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  const distance = earthRadius * c; // Distance between two points in meters
  
  return distance;
}